### ISSUE TITLE
Finish the LinearAlgebra functions

### ISSUE THREAD

**Issue by IlliaHryshchuk** [VladGribinchuk/FoundationBuilder#13]
- Finish the LinearAlgebra functions
- Implement openMP parallelism, if it can provide acceleration
- Write unit tests

**Comment by VladGribinchuk** [comment]
Implementing linear algebra functions, please, pay attention to the `distanceFromPointToLine` func. 
In general, it may have 2 cases, when point P is lying _within_ the area L and _out of_ the area L (point P1 at the image).
In the 1st case, the shortest distance will be the ortogonal segment D from point P to the line segment AB. In the 2nd case, the shortest distance will be the D1 segment connecting point and one of the closer ends of AB.
Please take this into account while implementing this function.
![image](https://user-images.githubusercontent.com/11663898/81157488-b18b1980-8f8f-11ea-8732-47dcad44f6eb.png)

**Comment by IlliaHryshchuk** [comment]
It is usefull clarification for us, we will take it into account
