### ISSUE TITLE
Finish the Polygon class

### ISSUE THREAD

**Issue by IlliaHryshchuk** [VladGribinchuk/FoundationBuilder#14]
Finish the Polygon class:
- Complete the comparison operators, polygonLength, area, orientation, centroid, closestTo, translate
- Implement openMP parallelism, if it can provide acceleration
- Write unit tests

**Comment by 1m8o5s** [comment]
@VladGribinchuk, I have question to translate function: in result centroid of polygon must be in point p? Or p is like distances, to move x-coordinate and y-coordinate of every point of polygon?

**Comment by VladGribinchuk** [comment]
p is a vector each point in polygon should be moved

**Comment by 1m8o5s** [comment]
> p is a vector each point in polygon should be moved

Thank you

**Comment by VladGribinchuk** [comment]
@1m8o5s From my point of view, this issue can be closed. Or do you plan some further work on this task?

**Comment by 1m8o5s** [comment]
> @1m8o5s From my point of view, this issue can be closed. Or do you plan some further work on this task?

Oh, I forgot to close task
