### ISSUE TITLE
Finish the Polygon class: convexHull, isConvexHull

### ISSUE THREAD

**Issue by IlliaHryshchuk** [VladGribinchuk/FoundationBuilder#16]
- Complete next methods: : convexHull, isConvexHull
- Implement openMP parallelism, if it can provide acceleration
- Write unit tests

**Comment by IlliaHryshchuk** [comment]
As i understood, the convexHull method have to build a convex hull from all the points of 3D model?
I mean that firstly we must move all points of 3D model to a plane (e.g. every point`s coordinate z = 0), and then we must build a convex hull from that points? and that hull will be a prototype of a foundation, right?

**Comment by VladGribinchuk** [comment]
> As i understood, the convexHull method have to build a convex hull from all the points of 3D model?
> I mean that firstly we must move all points of 3D model to a plane (e.g. every point`s coordinate z = 0), and then we must build a convex hull from that points? and that hull will be a prototype of a foundation, right?

Yes, you're right about prototype of foundation. But Polygon::convexHull() method builds convex hull only from points of 2D polygon object.

**Comment by VladGribinchuk** [comment]
Related PR was merged, so you can close this issue
