### ISSUE TITLE
Discuss the main connections and dependencies of the project, agree on the model of the project

### ISSUE THREAD

**Issue by IlliaHryshchuk** [VladGribinchuk/FoundationBuilder#17]
- Have a discussion about the main connections and dependencies of the project
- Agree on the model of the project

**Comment by VladGribinchuk** [comment]
@IlliaHryshchuk @1m8o5s @okrdima Team, what exactly do you want to discuss here? Let me please know your questions/suggestions

**Comment by IlliaHryshchuk** [comment]
We want to discuss the way that program will work after a user opens an application. I imagine it like this:
1. read stl model by `Mesh::read`
2.  "recognize" a shape of stl model by some algorythm, and create a convex hull by `Polygon::convexHull`
3. simplify it by `Polygon::simplify`
4. expand the convex hull by some algorythm
5. trangulate it by `Polygon::triangulate`
6. create the 3d model of foundation (reflect bottom, and create walls)
7.  place the foundation under a stl figure (if the apropraite flag is set)
8. write file by `Mesh::write`
9. create and write a metadata of a file

Is this algorythm correct?

**Comment by VladGribinchuk** [comment]
Yes, looks good. Probably, I would also add 0. step - parse input command line parameters.

UDP: @IlliaHryshchuk please close this task if no one has additional questions about high level idea of application workflow at the moment.

**Comment by IlliaHryshchuk** [comment]
> 0. step - parse input command line parameters.

Yes, it is compulsory.

Yes, we have already spoken about it with a team in messengers, so we don't have additional questions.
