### ISSUE TITLE
Complete Mesh class

### ISSUE THREAD

**Issue by IlliaHryshchuk** [VladGribinchuk/FoundationBuilder#19]
- Complete Mesh class
- Complete methods for reading and writing STL files (create STL parser)
- Implement openMP parallelism, if it can provide acceleration
- Write unit tests

**Comment by IlliaHryshchuk** [comment]
Should we read only points in the `Mesh class`? What about normals of facets and comment? And why don't we unite points into triangles?
something like that:
`struct Facet {
Triangle3D facet;
FPoint3D normal;
};
std::vector<Facet> facets;`

![image](https://user-images.githubusercontent.com/45259941/82308449-7b578c00-99ca-11ea-8625-f473bbbd61ce.png)

**Comment by VladGribinchuk** [comment]
You can do whatever you consider the best approach) I argee, maybe it would be better to go with Triangle vector. But additionally storing normals myabe is overhead - normal could be easily computed for triangle if needed (you can add this method to triangle class if it isn't present here).
We can add additional data field in future, if needed

**Comment by IlliaHryshchuk** [comment]
Ok, i will try to do it)

**Comment by IlliaHryshchuk** [comment]
and what about openMP in read/write functions? I have read that it is not the best idea to use parallel reading/writing, however it is possible. In the unit tests seems like it works, but there i've used meshes with 1-2 facets, so i don't know how it will behave with huge files

**Comment by VladGribinchuk** [comment]
> and what about openMP in read/write functions? I have read that it is not the best idea to use parallel reading/writing, however it is possible. In the unit tests seems like it works, but there i've used meshes with 1-2 facets, so i don't know how it will behave with huge files

You're right - parallel reading/writing from/into files is rather perversion than something normal) 

Operating System provides only sequential access for reading/writing file descriptors, so it's no sense to parallelize such operations. Efforts spent on designing parallel algorithm, consequently will be nullified because of OS synchronization mechanism for file descriptors.
