### ISSUE TITLE
Complete the Application::init method and CommandLine class

### ISSUE THREAD

**Issue by IlliaHryshchuk** [VladGribinchuk/FoundationBuilder#20]
- Complete the Application::init method
- Complete CommandLine class (implement parsing of command line parameters)
- Implement openMP parallelism, if it can provide acceleration
- Write unit tests

**Comment by IlliaHryshchuk** [comment]
May be first 2 comments from issue [20](https://github.com/VladGribinchuk/FoundationBuilder/issues/24) would be useful for this task

**Comment by okrdima** [comment]
@VladGribinchuk Can I take your example to complete the task? From VG-CommandLine-Example

**Comment by VladGribinchuk** [comment]
Yes,sure. This example was implemented exactly for this task. Please create your own branch and use code in VG-CommanndLine-Example as an example. Understand how things work, copy code, modify/improve it, if needed, and then set up proper parameters for FondationBuilder application as it was required by specification.

**Comment by okrdima** [comment]
@VladGribinchuk 
In CommandLine the following points should be implemented:
1)InputModel(file path);
2)OutPutModel(file path);
3)MetaDate(true/false);
4)BuildIn(true/false);
5)ASCII/Binary file(true/false);
6)Height(number);
7)Help
?

**Comment by VladGribinchuk** [comment]
Yes, except that Metadata parameter is output file path also

**Comment by okrdima** [comment]
@VladGribinchuk Do I need to write UniTtests for this task?

**Comment by VladGribinchuk** [comment]
No, you dont, for now. We will add several **functional** test cases later, when application will be completed and Illya will prepare some ground.

**Comment by okrdima** [comment]
@VladGribinchuk Data transferred from the console must be stored in CommandLine or Application?Do I need to write data to CommandLine and then pass it to Application?

**Comment by VladGribinchuk** [comment]
Cannot answer definitely. Think about what each class should be responsible for. And try to find the best architecting approach. However your goal is implement only logic of parsing command line parameters. Any further relations and connections will be implemented afterwards.
Anyway suggest your version of implementation and discuss it with the team in pull request.
