### ISSUE TITLE
Create the main method for implementation of a foundation

### ISSUE THREAD

**Issue by IlliaHryshchuk** [VladGribinchuk/FoundationBuilder#21]
- Create a method for implementation of a foundation
- Implement openMP parallelism, if it can provide acceleration
- Write unit tests

**Comment by VladGribinchuk** [comment]
@1m8o5s 

- The goal of this task is to implement algorithm outlined at #18 (actually, steps from 2 to 9). 
- The output of this task will be method:
`Mesh createFoundation(const Mesh& inputModel) { ... }`
This method should take the input 3D model as parameter `inputModel`, calculate 3D foundation geometry for it and return foundation as new Mesh object.

All further work with integrating this method into Application workflow will be done after. Your goal is to implement **only one block** of Application: calculation of foundation. You can start working on it, even if related functions - simplification, polygon inflation - are haven't done yet. Create stubs for these methods (if they aren't created) and leave these stubs. These methods could be implemented after.

**Comment by 1m8o5s** [comment]
> @1m8o5s
> 
> * The goal of this task is to implement algorithm outlined at #18 (actually, steps from 2 to 9).
> * The output of this task will be method:
>   `Mesh createFoundation(const Mesh& inputModel) { ... }`
>   This method should take the input 3D model as parameter `inputModel`, calculate 3D foundation geometry for it and return foundation as new Mesh object.
> 
> All further work with integrating this method into Application workflow will be done after. Your goal is to implement **only one block** of Application: calculation of foundation. You can start working on it, even if related functions - simplification, polygon inflation - are haven't done yet. Create stubs for these methods (if they aren't created) and leave these stubs. These methods could be implemented after.

Ok, I start working with this method

**Comment by VladGribinchuk** [comment]
@1m8o5s How things are going with this task? Do you have any questions or do you need some help?

**Comment by VladGribinchuk** [comment]
> How things are going with this task? Do you have any questions or do you need some help?

@1m8o5s FYI, if you are asked that type of questions, it means please reply asap with your current progress status. Also, in that way you are politely asked to hurry up.

We've already failed all deadlines so we should complete this ASAP and move on. Let me know if you need help

**Comment by 1m8o5s** [comment]
Oh, sorry, my bad, I not often check messages. Now I try to get vertices of input figure, which don`t duplicate

**Comment by VladGribinchuk** [comment]
Why do you need vertices which dont duplicate?

**Comment by 1m8o5s** [comment]
![photo_2020-06-09_23-53-07](https://user-images.githubusercontent.com/24863477/84236094-bfd4d400-aaff-11ea-8150-b76f2a837d07.jpg)
I wanted to do this, because I think that can damage performance, like in this picture vertice "a" used in 8 triangles

**Comment by 1m8o5s** [comment]
In general this method works, but now I fix it, because disproportionate foundation comes out in result

**Comment by VladGribinchuk** [comment]
Sorry, but still don't understand you clearly. The goal is to create well-defined 3d foundation structure, i.e. without holes, self-intersections, etc. And what do you mean for 'disproportionate foundation'?

> vertice "a" used in 8 triangles

I don't see the problem here.

Anyway, if you are able, could you please show how your implementation works at the moment?

**Comment by 1m8o5s** [comment]
![image](https://user-images.githubusercontent.com/24863477/84245174-5491fe80-ab0d-11ea-82bc-b49af33250c5.png)
for this input figure in result we have that foundation:
![image](https://user-images.githubusercontent.com/24863477/84245324-899e5100-ab0d-11ea-9c32-30b29b47c9c0.png)

**Comment by VladGribinchuk** [comment]
Kinda what we need... okay, finish your fixes or whatever you're working at, and push changes

**Comment by VladGribinchuk** [comment]
@1m8o5s you can close this
