### ISSUE TITLE
Create the integration method (placing foundation under the figure)

### ISSUE THREAD

**Issue by IlliaHryshchuk** [VladGribinchuk/FoundationBuilder#23]
- Create the integration method (placing foundation under the figure)
- Implement openMP parallelism, if it can provide acceleration
- Write unit tests

**Comment by okrdima** [comment]
@VladGribinchuk 
The team has an idea how to do it.
1) Find the smallest value of z, from input Figure.
2) In the upper part of the value of z replace with the value obtained from the input Figure, in the lower part of the value of =  z - height.

What do you think about it?

**Comment by VladGribinchuk** [comment]
Yup, looks right

**Comment by okrdima** [comment]
@VladGribinchuk  Integration method should be placed in Mesh class?

**Comment by VladGribinchuk** [comment]
From my point of view, the integration method is sort of 'merging of two Mesh objects', because we will have original mesh and foundation mesh. And how you will implement this method is up to you. It can be free function or really can be part of Mesh class. 
But I think you should wait for related issue #21 to be done firstly, because how will you integrate without actually foundation implemented.

**Comment by okrdima** [comment]
@VladGribinchuk  Judging by what I saw in the request, do I need to create a method that will simply change the z so that the foundation is under the figure (as I described in the previous mess)?

**Comment by VladGribinchuk** [comment]
Yes.
Lets clarify. Please create free function `Mesh integrateFoundationIntoModel(const Mesh& model, const Mesh& foundation);`, which takes two mesh objects as arguments and return new Mesh object containing the `model` merged with the `foundation` (placed beneath the model).
Also, please add some small gap between the foundation and the model to not introduce self-intersections inside the geometry. Gap can be 1.0mm size.

**Comment by VladGribinchuk** [comment]
@okrdima now we have method for the construction of foundation, so you can start work on this task. Let's finish this as soon as possible, this is almost the last effort.

**Comment by okrdima** [comment]
@VladGribinchuk  Make the gap constant or pass it as a parameter to a function?

**Comment by VladGribinchuk** [comment]
Make it constant 1mm

**Comment by okrdima** [comment]
@VladGribinchuk  To save height I find it using in height = abs(Zmax) - abs(Zmin)?

**Comment by VladGribinchuk** [comment]
Sorry, I didn't get the question. Could you please rephrase?

**Comment by okrdima** [comment]
I wanto to change zMaxFoundation = zMinModel - gap, zMinFoundation = zMinModel - gap-height. Where do I get the height of the foundation? Height is a parameter that is set in the console. But the function gets a ready foundation object, therefore, the height of the foundation I can get so height = abs(zMaxFoundation) - abs(zMinFoundation)

**Comment by VladGribinchuk** [comment]
Yes, height of foundation is its max z-coord minus min z-coord. 
BTW, why do you need to compute abs() of these values? This will lead to wrong results. Height is just the difference between top and bottom z-coords.

**Comment by okrdima** [comment]
Yup, thank you
