### ISSUE TITLE
Complete Application class

### ISSUE THREAD

**Issue by IlliaHryshchuk** [VladGribinchuk/FoundationBuilder#24]
- Complete Application class
- Implement general workflow for application based on input parameters
- Implement openMP parallelism, if it can provide acceleration
- Write unit tests

**Comment by IlliaHryshchuk** [comment]
is it OK to parse parameters in this [way](https://github.com/VladGribinchuk/FoundationBuilder/blob/52f37329ad9fb234d7dfc8c517c75158700d712c/FoundationBuilder/src/Application.cpp#L7) ?
I did not use `CommandLine::getValue`, and i did not understand exactly what to do in `CommandLine::isSpecified`, so i am not sure that it is correct implementation.

and how to write UnitTests for methods that interact with `argc` and `argv`? For testing it in debugger i set parameters in properties->debugging->Command arguments. Should i do the same for UnitTests project?

**Comment by VladGribinchuk** [comment]
We have #20 task for CommandLine implementation. Have you re-assigned this work?

Anyway, this is what I am thinking about your implementation of CommandLine. It should be more flexible and scalable, i.e. it should allow new parameters to be easily added in future if needed or old parameters to be modified without large changes. For example, if suddenly we must modify some old parameter or add new, then your current implementation require quite large amount of changes in CommandLine::parse(), isSpecified() methods. Instead, it would be better if we have more flexible system of specifying and fetching program parameters, which would allow us to do it literally in one line change. Also, CommandLine should provide some feedback if there are something wrong with input parameters or some crucial parameter is not specified - for example, output help info.

So, if you work on this task, please make time and try to research more flexible solution for parsing program options. Let me know the results.

Another topic is **tests for FoundationBuilder application**. This is what I suggest. 
- add some post-build step to FoundationBuilder project, which will copy fresh FoundationBuilder.exe build to working folder of UnitTests project
- write test cases which will use `system()` call to launch execution of FoundationBuilder. It will be smth like this: system("./FoundationBuilder.exe _...different parameters_"). Then check results of launching. For example, specify some parameters, then check if output STL satisfies requirements, or output metadata file contains correct data, etc.

Thus, these unit tests for FoundationBuilder will be rather **functional** testing than **unit**. But anyway, we can use our UnitTests framework for this. By the way, all this is good candidate for new issue, for example, "Setup tests for FoundationBuilder application".

**Comment by IlliaHryshchuk** [comment]
> We have #20 task for CommandLine implementation. Have you re-assigned this work?

No, i have not re-assigned this work. Seems that i did not understand my issue. So, i have to work just with Application class? Only `Init` and `run` methods? As i understood, that methods must use  already written methods from another classes, and i can do it only when all other issues will be done? (like the main purpose of #24 issue is to gether all methods, and " compose" them?) Anyway, i have tried to do something like "sceleton", here it is:
![image](https://user-images.githubusercontent.com/45259941/82893951-81b1af00-9f5a-11ea-85f4-ac50e8ff291a.png)


> By the way, all this is good candidate for new issue, for example, "Setup tests for FoundationBuilder application".

the #24 issue looks a little small, so i will assign unit tests for me

**Comment by VladGribinchuk** [comment]
Yes, this task is, like you wrote, task for composing all blocks together. So, seems like you really have to wait until the rest team will provide you with those blocks by implementing their tasks. You can do some skeleton now, but it will be very raw at the moment. Wait please for accomplishment of at least #20 and #21 tasks. 
My advice: ping your teammates to speed up their work) For example, #15 Polygon class should be done asap.

Meanwhile please create task "Setup tests for FoundationBuilder application" and work on it. You don't have to write any test cases for FoundationBuilder at the moment. Just prepare ground + maybe one simple example.

**Comment by IlliaHryshchuk** [comment]
Ok, i will do it

**Comment by VladGribinchuk** [comment]
@IlliaHryshchuk Looks like all is ready for this task.
Also, please make some refactoring at the same time: move createFoundation and integrateFounadion functions out of GeometryCore and put inside FoundationBuilder. Because here is the concept of GeometryCore - it is geometric library containing primitives and general functions. And above mentioned functions dont fit the concept, since they are specialized functions. Logically they are the parts of FoundationBuilder. Do you agree?

As for unit tests for those functions, please convert them into 'functional', I mean which will be launched via system("FoudationBuilder...")

**Comment by IlliaHryshchuk** [comment]
> Looks like all is ready for this task.

Almost yes, but we still don't have a metadata. I have written some code without it, and I will add it as soon as metadata method will be done.



> Do you agree?

Yes, I agree with it. So, I will move that functions, and do commit after that.

> As for unit tests for those functions, please convert them into 'functional', I mean which will be launched via system("FoudationBuilder...")

I was trying to do something like that, hope that i have done what we need)

**Comment by IlliaHryshchuk** [comment]
Does somebody have an imagine why could that errors occur?
I was trying to move functions from `Mesh `to `FoundationBuilder`:
 - I have created 2 files in FoundationBuilder (`.h` and` .cpp`)
 - moved 2 functions from `Mesh `to my files
 - included in new files all headers, that was in `Mesh `files
 - used namespace in new files
 - included` .h` file in `.cpp` file
 - included new` .h` file in `MeshTests.h`

Errors occur only while building the project. If i comment all tests with that functions - project is building well.
That 2 functions also work well in `Application::run()`

![image](https://user-images.githubusercontent.com/45259941/84576781-022c3880-adc0-11ea-94b0-7ef4742b9c57.png)

**Comment by VladGribinchuk** [comment]
Here is the problem. When you build UnitTests, linker cannot find definitions of `createFoundation` and `integrateFoundation`, because those definitions are in .cpp in FoundationBuilder project now. Linker see only header with declaration of those function, but it has no access to definitions. It was building well previously, when those functions were in GeometryCore, because UnitTests links with GeometryCore.lib. And it isn't building now, because UnitTests has no linkage with FoundationBuilder.
Simply, you cannot use functions declared in FoundationBuilder project for UnitTests (that is why, I added task for creating special test cases for FoundationBuilder).
Let me please know, if my explanation is clear.

**Comment by IlliaHryshchuk** [comment]
Yes, i have understood, thanx. So what to do with unit tests for that functions? Should i re-write them?
A will commit my local branch in few minutes to show what i have

**Comment by VladGribinchuk** [comment]
As I said, please convert those test into 'functional', which will be launched via system("FoudationBuilder..."). But this part of work seems like in the scope of #40 issue.

Anyway, for example we had this code:
```
    model.read("../test_models/cube_20x20x20_ascii.stl");
    Mesh fonundation = createFoundation(model, 4.00, 5.00);
    Mesh out = integrateFoundationIntoModel(model,fonundation);

    AABB3D box(FPoint3D(-15.001, -15.001, -5.001), FPoint3D(20.001, 20.001, 20.001));
    for (auto i : out.getFacets()) {
        TEST_ASSERT((box.contains(i.a) && box.contains(i.b) && box.contains(i.c)), "All points must be in Axis Aligned Boundary Box");
    }
```

it can be converted to smth like this (below is pseudo code):
```
call system("FoundationBuilder...") with parameters launching FoundationBuilder with input model "../test_models/cube_20x20x20_ascii.stl", height equal to 4, inflate equal to 5, enabling built-in foundation;
read generated stl;
check whether its bounding box correspond expectations;
```

**Comment by IlliaHryshchuk** [comment]
Yes, if i understand correctly, i have written that tests in [ApplicationTests.h](https://github.com/VladGribinchuk/FoundationBuilder/blob/9e466013ec4942e0a3d400a5ada48b69765808a1/UnitTests/ApplicationTests.h#L5).
But I had to comment tests in [MeshTests.h](https://github.com/VladGribinchuk/FoundationBuilder/blob/9e466013ec4942e0a3d400a5ada48b69765808a1/UnitTests/MeshTests.h#L129) to compile the project correctly. And I mean that we can't test `createFoundation()` and `integrateFoundationIntoModel()` separately anymore?

Also i have implemented [Application::run()](https://github.com/VladGribinchuk/FoundationBuilder/blob/9e466013ec4942e0a3d400a5ada48b69765808a1/FoundationBuilder/src/Application.cpp#L36), does it look OK in this implementation?

upd:
Oh, i have understood what to do. I will "Combine" previous tests with my test

**Comment by VladGribinchuk** [comment]
Yes, all look good. You understood correctly. If you decide to leave MeshTests.h commented out, then do not forgot to restore those cases in future in the manner you made it in ApplicationTests.h. And... about using `#include <windows.h>` and exotic `struct stat buffer;` 
Let's create cross platform code. And we will not depend on specific platform headers, like <windows.h>. We will use only standard C++. So, in case if our Customer will want to switch to Unix-like system, we can do it easily.
So, you need to remove `#include <windows.h>` and provide your implementation of `CopyFile` and function to check if file exist.

**Comment by IlliaHryshchuk** [comment]
Ok, i will do it

**Comment by VladGribinchuk** [comment]
Quick tip from me, to lighten a bit your work.
`inline bool isFileExist(string file) { return std::ifstream(file); }`
`ifstream` defines  `operator bool`, i.e. conversion to bool, and it will have true value if there is no any error, and false otherwise.
In the same way, you can use standart C++ ifstream, ofstream to copy file

**Comment by IlliaHryshchuk** [comment]
> Quick tip from me, to lighten a bit your work.

thanx)
