### ISSUE TITLE
Сheck the result

### ISSUE THREAD

**Issue by IlliaHryshchuk** [VladGribinchuk/FoundationBuilder#25]
- Сheck the correctness of the project
- Compare the result with initial task
- Create Bug Issue if some bug was found

**Comment by VladGribinchuk** [comment]
I want to see the results in the following way. PDF document, containing table with the following columns: 
- **test model name**
- **test model picture** (actully, small screen of the model)
- **foundation parameters** (used height, inflate, built-in, etc. values)
- **foundation picture** (small screen of created foundation)
- **resume** (your conclusion on whether program processed this model correctly or not, and if not - what is wrong)

You should check all test models containing in repository + 3 additional STL model with non-trivial geometry(I mean, not just cube or square, etc.) downloaded from any free internet resources. Try several cases for each model, for example, different height/inflate values, built-in parameter switched off/on.

Please split all these work between each team member, but combine the results into one document. This pdf document is the output for this task. Attach it here in comments after finishing.

**Comment by IlliaHryshchuk** [comment]
Ok, we will divide the work, and create a document.

**Comment by okrdima** [comment]
@VladGribinchuk We created a document, what to do with it?

**Comment by IlliaHryshchuk** [comment]
Here is our file: [modelsTable.pdf](https://github.com/VladGribinchuk/FoundationBuilder/files/4785282/modelsTable.pdf)
We have added a little bit more screenshots, this process was very interesting and fascinating)

**Comment by VladGribinchuk** [comment]
Good job! Based on yours test we can conclude Application is working as expected. Unit tests are also running without failure, which is good. So, the only one thing has left is metadata output, #31.

**Comment by IlliaHryshchuk** [comment]
> Good job!

Thanx) So, this issue may be closed?

**Comment by VladGribinchuk** [comment]
I guess, yes, you may close this. But do not forget to make a quick regressiong testing, without documenting, after adding new metadata functionality (whether all is working correctly and new functionality don't break anything). Make this after pull request creation

**Comment by IlliaHryshchuk** [comment]
Ok, we will do it before writing a finish reports
