### ISSUE TITLE
Prepare finish reports

### ISSUE THREAD

**Issue by IlliaHryshchuk** [VladGribinchuk/FoundationBuilder#27]
- Create own report
- Sum up all learned new information and gained skills
- Describe all solved/unsolved troubles

**Comment by VladGribinchuk** [comment]
@IlliaHryshchuk @okrdima @1m8o5s guys, this is the last effort) each of you please prepare yours finish reports and attach those here.

**Comment by IlliaHryshchuk** [comment]
Here is my report: [Finish report (Illia Hryshchuk).pdf](https://github.com/VladGribinchuk/FoundationBuilder/files/4798080/Finish.report.Illia.Hryshchuk.pdf). It not looks like a "typical" report as in university, it is a kind of "speech". Is it ok?)

**Comment by VladGribinchuk** [comment]
Yes, it is ok, informal style is welcome. Thanks, @IlliaHryshchuk it was good to hear such words!

**Comment by 1m8o5s** [comment]
[finish report.pdf](https://github.com/VladGribinchuk/FoundationBuilder/files/4803578/finish.report.pdf)

**Comment by VladGribinchuk** [comment]
I'm glad if you liked this format) and thanks @1m8o5s 

@okrdima I'm waiting for your report

**Comment by okrdima** [comment]
[Report okrdima.pdf](https://github.com/VladGribinchuk/FoundationBuilder/files/4809513/Report.okrdima.pdf)
I wanted to make it beautiful, but it didn't work out, so I left it as it is

**Comment by VladGribinchuk** [comment]
Nice, thanks @okrdima! I really appreciate all yours feedback and hope you will develop yourself)

Team Lead now can close this last issue
