### ISSUE TITLE
TASK FROM CUSTOMER: metadata output

### ISSUE THREAD

**Issue by VladGribinchuk** [VladGribinchuk/FoundationBuilder#31]
Since the requirements for singlethreading/multithreading execution has slightly changed (lightened), the requirement for input command line parameter `-m` was also changed (clarified). 

This parameter should enable outputting of metadata about foundation in this manner:
`-m file/path/to/metadata_file`

Metadata file should contain the following info, in JSON like style:
{
"model": {
name: "_input model file name_",
bbox: [_xmin, xmax, ymin, ymax, zmin, zmax_]
},
"foundation": {
name: "_output file name_",
bbox: [_xmin, xmax, ymin, ymax, zmin, zmax_],
is_build_in: _true/false_,
height: _value_in_mm_,
polygon_length: _value_in_mm_,
polygon_area: _value_in_mm2_,
num_of_facets: _count_,
time_of_constructing: _time_in_ms_
}
}

P.S.
Team Lead should assign this task to someone

**Comment by IlliaHryshchuk** [comment]
We have discussed it in the team, and the decision is that this task will be taken by dev#3 Mykola. Because dev#2 Dmytro has more issues than me and Mykola, and i have already done part of Mykola`s issue

**Comment by VladGribinchuk** [comment]
> We have discussed it in the team, and the decision is that this task will be taken by dev#3 Mykola. Because dev#2 Dmytro has more issues than me and Mykola, and i have already done part of Mykola`s issue

Agreed

**Comment by VladGribinchuk** [comment]
@1m8o5s please start working on this task. Please create a free function accepting Mesh model, Mesh foundation, and most likely some other additional parameters, for example, file paths. All properties of model and foundation should be computed based on provided Mesh objects.

**Comment by 1m8o5s** [comment]
Ok, all that i cant get from foundation and input model i will get from parameters

**Comment by VladGribinchuk** [comment]
Code changes were merged. Please, do a quick regression testing on some models. And close this task if all is working well.

**Comment by 1m8o5s** [comment]
Tests on models working well
