### ISSUE TITLE
Performance of convexHull()

### ISSUE THREAD

**Issue by VladGribinchuk** [VladGribinchuk/FoundationBuilder#34]
Here is the screen of recently added performance tests for Polygon::convexHull()
![image](https://user-images.githubusercontent.com/11663898/82127614-b46ee100-97bd-11ea-9a7e-0a5ea024fca2.png)
tests were run with Release build on the machine: 3.1GHz, 4-core CPU.

As you may see convexHull computation took in average 22ms for polygon with 10000 points and 237ms for 100000 points polygon. Looks like current convexHull algorithm is working correct and fast enough. Nevertheless, this is one of the key function the whole project, so I'm wondering if we may still speed it up.

**My suggestion:**
Please review this monotone chain algorithm for convex hull: https://en.wikibooks.org/wiki/Algorithm_Implementation/Geometry/Convex_hull/Monotone_chain.
Try to implement this alternative algorithm in our project. It would not take much time, since there is already C++ implementation present, just adapt it to our code. Compare performance of current convexHull implementation and this alternative version. If you will see notable divergence in performance, please try to figure out and explain why.
**Note:** this is not a bug, but consider this task as a research and possible improving work. It's not high-priority, but still it should be done.

**Comment by VladGribinchuk** [comment]
@IlliaHryshchuk maybe you fit for this task the best, since you has already implemented convexHull. But final decision to assign this task for someone I leave to you.
@1m8o5s @okrdima FYI

**Comment by IlliaHryshchuk** [comment]
It is interesting very much if we could improve the performance! I will take this issue, because i have worked with convexHull, and i have the least number of tasks now. 

> **Note:** this is not a bug, but consider this task as a research and possible improving work. It's not high-priority, but still it should be done.

but if this task is not in high-priority, i will do it after my 2 current tasks

**Comment by IlliaHryshchuk** [comment]
i have two kinds of errors:
first error:
![image](https://user-images.githubusercontent.com/45259941/82937421-cd834900-9f98-11ea-9ae0-d469cd5e58f7.png)
second error:
![image](https://user-images.githubusercontent.com/45259941/82937487-e5f36380-9f98-11ea-8742-61d8126db40c.png)

they occure when i am trying to sort points of Polygon: `std::sort(this->points.begin(), this->points.end());`. May be you have any ideas how to fix it? I tried everything I could do, and i don't know how to solve it

**Comment by VladGribinchuk** [comment]
To `std::sort` 'something', you should be sure, that this something can be compared by operator< less. This is how std::sort is working, it compares items in array by operator<. If something cannot be compared, then there is an error. Point is custom type, so to fix error you should provide comparison operator fot this type. **Or** you can use overloaded std::sort(), which takes third argument - predicate, and compare items by this predicate.

P.S. by the way, operator= should be non-const, because it modifies internall data fields (this is why you have second error - you try to modify x and y inside const method.

**Comment by IlliaHryshchuk** [comment]
i have overloaded operator: 
`    template<typename T>
    constexpr bool operator< (const Point2D<T>& lhs, const Point2D<T>& rhs) { return lhs.x < rhs.x || (lhs.x == rhs.x && lhs.y < rhs.y); }`

and i have tried to do it with lambda:
`auto lexicographicallyPred = [](const FPoint2D& a, const FPoint2D& b) {return a.x < b.x || (a.x == b.x && a.y < b.y); };`
`std::sort(this->points.begin(), this->points.end(), lexicographicallyPred);` 

But i got the same result, so i decided that it is connected with "=", and thats why i was trying to write `operator=`. May be something wrong with my operator< and predicate?

**Comment by VladGribinchuk** [comment]
I see that you try to do sort on `this->points`. So, please check if you not try to do this inside `const` method. Because you cannot modify class data field inside const method.
If so, you should firstly copy points to modifiable object: `auto pointsCopy = this->points;` and try sort on `pointsCopy`.

**Comment by IlliaHryshchuk** [comment]
oh, the answer was so obvious, thanks, this method is really constant) now everything works correct.
