### ISSUE TITLE
Setup tests for FoundationBuilder application

### ISSUE THREAD

**Issue by IlliaHryshchuk** [VladGribinchuk/FoundationBuilder#40]
- write unit/functional tests for FoundationBuilder application

**Comment by IlliaHryshchuk** [comment]
Is it OK that during testing i get additional information in console window with tests? Or I should test program in separate cmd window somehow? (I have used `system("FoundationBuilder.exe -help");` here)

![image](https://user-images.githubusercontent.com/45259941/84526397-e3f20a00-ace5-11ea-9cfc-60eb10ff00e2.png)

**Comment by VladGribinchuk** [comment]
It's not OK, in fact) 
Lets see what you can do.. in theory, you can redirect output to some temporary file `FoundationBuilder.exe -help > temporary.file`. 
And if you need to check the output of FoundationBuilder.exe call, then just read the file. Please try whether this is working.

**Comment by IlliaHryshchuk** [comment]
Yes, it works perfectly! Thanx)
